### ISSUE TITLE
Skeleton

### ISSUE THREAD

**Issue by portlek** [Infumia/InfumiaPlugin#1]

**Comment by portlek** [comment]
`implement Addond`

**Comment by 0pdd** [comment]
@portlek 6 puzzles [#509](https://github.com/Infumia/InfumiaLib/issues/509), [#510](https://github.com/Infumia/InfumiaLib/issues/510), [#546](https://github.com/Infumia/InfumiaLib/issues/546), [#547](https://github.com/Infumia/InfumiaLib/issues/547), [#548](https://github.com/Infumia/InfumiaLib/issues/548), [#549](https://github.com/Infumia/InfumiaLib/issues/549) are still not solved.

**Comment by 0pdd** [comment]
@portlek 2 puzzles [#509](https://github.com/Infumia/InfumiaLib/issues/509), [#510](https://github.com/Infumia/InfumiaLib/issues/510) are still not solved; solved: [#546](https://github.com/Infumia/InfumiaLib/issues/546), [#547](https://github.com/Infumia/InfumiaLib/issues/547), [#548](https://github.com/Infumia/InfumiaLib/issues/548), [#549](https://github.com/Infumia/InfumiaLib/issues/549).

**Comment by 0pdd** [comment]
@portlek the puzzle [#509](https://github.com/Infumia/InfumiaLib/issues/509) is still not solved; solved: [#510](https://github.com/Infumia/InfumiaLib/issues/510), [#546](https://github.com/Infumia/InfumiaLib/issues/546), [#547](https://github.com/Infumia/InfumiaLib/issues/547), [#548](https://github.com/Infumia/InfumiaLib/issues/548), [#549](https://github.com/Infumia/InfumiaLib/issues/549).

**Comment by 0pdd** [comment]
@portlek 2 puzzles [#509](https://github.com/Infumia/InfumiaLib/issues/509), [#624](https://github.com/Infumia/InfumiaLib/issues/624) are still not solved; solved: [#510](https://github.com/Infumia/InfumiaLib/issues/510), [#546](https://github.com/Infumia/InfumiaLib/issues/546), [#547](https://github.com/Infumia/InfumiaLib/issues/547), [#548](https://github.com/Infumia/InfumiaLib/issues/548), [#549](https://github.com/Infumia/InfumiaLib/issues/549).

**Comment by 0pdd** [comment]
@portlek the puzzle [#509](https://github.com/Infumia/InfumiaLib/issues/509) is still not solved; solved: [#510](https://github.com/Infumia/InfumiaLib/issues/510), [#546](https://github.com/Infumia/InfumiaLib/issues/546), [#547](https://github.com/Infumia/InfumiaLib/issues/547), [#548](https://github.com/Infumia/InfumiaLib/issues/548), [#549](https://github.com/Infumia/InfumiaLib/issues/549), [#624](https://github.com/Infumia/InfumiaLib/issues/624).

**Comment by 0pdd** [comment]
@portlek 2 puzzles [#509](https://github.com/Infumia/InfumiaLib/issues/509), [#633](https://github.com/Infumia/InfumiaLib/issues/633) are still not solved; solved: [#510](https://github.com/Infumia/InfumiaLib/issues/510), [#546](https://github.com/Infumia/InfumiaLib/issues/546), [#547](https://github.com/Infumia/InfumiaLib/issues/547), [#548](https://github.com/Infumia/InfumiaLib/issues/548), [#549](https://github.com/Infumia/InfumiaLib/issues/549), [#624](https://github.com/Infumia/InfumiaLib/issues/624).

**Comment by 0pdd** [comment]
@portlek 5 puzzles [#635](https://github.com/Infumia/InfumiaLib/issues/635), [#636](https://github.com/Infumia/InfumiaLib/issues/636), [#637](https://github.com/Infumia/InfumiaLib/issues/637), [#638](https://github.com/Infumia/InfumiaLib/issues/638), [#639](https://github.com/Infumia/InfumiaLib/issues/639) are still not solved; solved: [#509](https://github.com/Infumia/InfumiaLib/issues/509), [#510](https://github.com/Infumia/InfumiaLib/issues/510), [#546](https://github.com/Infumia/InfumiaLib/issues/546), [#547](https://github.com/Infumia/InfumiaLib/issues/547), [#548](https://github.com/Infumia/InfumiaLib/issues/548), [#549](https://github.com/Infumia/InfumiaLib/issues/549), [#624](https://github.com/Infumia/InfumiaLib/issues/624), [#633](https://github.com/Infumia/InfumiaLib/issues/633).

**Comment by 0pdd** [comment]
@portlek 8 puzzles [#637](https://github.com/Infumia/InfumiaLib/issues/637), [#638](https://github.com/Infumia/InfumiaLib/issues/638), [#639](https://github.com/Infumia/InfumiaLib/issues/639), [#642](https://github.com/Infumia/InfumiaLib/issues/642), [#643](https://github.com/Infumia/InfumiaLib/issues/643), [#644](https://github.com/Infumia/InfumiaLib/issues/644), [#645](https://github.com/Infumia/InfumiaLib/issues/645), [#646](https://github.com/Infumia/InfumiaLib/issues/646) are still not solved; solved: [#509](https://github.com/Infumia/InfumiaLib/issues/509), [#510](https://github.com/Infumia/InfumiaLib/issues/510), [#546](https://github.com/Infumia/InfumiaLib/issues/546), [#547](https://github.com/Infumia/InfumiaLib/issues/547), [#548](https://github.com/Infumia/InfumiaLib/issues/548), [#549](https://github.com/Infumia/InfumiaLib/issues/549), [#624](https://github.com/Infumia/InfumiaLib/issues/624), [#633](https://github.com/Infumia/InfumiaLib/issues/633), [#635](https://github.com/Infumia/InfumiaLib/issues/635), [#636](https://github.com/Infumia/InfumiaLib/issues/636).

**Comment by 0pdd** [comment]
@portlek 5 puzzles [#637](https://github.com/Infumia/InfumiaLib/issues/637), [#638](https://github.com/Infumia/InfumiaLib/issues/638), [#639](https://github.com/Infumia/InfumiaLib/issues/639), [#642](https://github.com/Infumia/InfumiaLib/issues/642), [#645](https://github.com/Infumia/InfumiaLib/issues/645) are still not solved; solved: [#509](https://github.com/Infumia/InfumiaLib/issues/509), [#510](https://github.com/Infumia/InfumiaLib/issues/510), [#546](https://github.com/Infumia/InfumiaLib/issues/546), [#547](https://github.com/Infumia/InfumiaLib/issues/547), [#548](https://github.com/Infumia/InfumiaLib/issues/548), [#549](https://github.com/Infumia/InfumiaLib/issues/549), [#624](https://github.com/Infumia/InfumiaLib/issues/624), [#633](https://github.com/Infumia/InfumiaLib/issues/633), [#635](https://github.com/Infumia/InfumiaLib/issues/635), [#636](https://github.com/Infumia/InfumiaLib/issues/636), [#643](https://github.com/Infumia/InfumiaLib/issues/643), [#644](https://github.com/Infumia/InfumiaLib/issues/644), [#646](https://github.com/Infumia/InfumiaLib/issues/646).

**Comment by 0pdd** [comment]
@portlek 3 puzzles [#638](https://github.com/Infumia/InfumiaLib/issues/638), [#639](https://github.com/Infumia/InfumiaLib/issues/639), [#642](https://github.com/Infumia/InfumiaLib/issues/642) are still not solved; solved: [#509](https://github.com/Infumia/InfumiaLib/issues/509), [#510](https://github.com/Infumia/InfumiaLib/issues/510), [#546](https://github.com/Infumia/InfumiaLib/issues/546), [#547](https://github.com/Infumia/InfumiaLib/issues/547), [#548](https://github.com/Infumia/InfumiaLib/issues/548), [#549](https://github.com/Infumia/InfumiaLib/issues/549), [#624](https://github.com/Infumia/InfumiaLib/issues/624), [#633](https://github.com/Infumia/InfumiaLib/issues/633), [#635](https://github.com/Infumia/InfumiaLib/issues/635), [#636](https://github.com/Infumia/InfumiaLib/issues/636), [#637](https://github.com/Infumia/InfumiaLib/issues/637), [#643](https://github.com/Infumia/InfumiaLib/issues/643), [#644](https://github.com/Infumia/InfumiaLib/issues/644), [#645](https://github.com/Infumia/InfumiaLib/issues/645), [#646](https://github.com/Infumia/InfumiaLib/issues/646).

**Comment by 0pdd** [comment]
@portlek 2 puzzles [#638](https://github.com/Infumia/InfumiaLib/issues/638), [#642](https://github.com/Infumia/InfumiaLib/issues/642) are still not solved; solved: [#509](https://github.com/Infumia/InfumiaLib/issues/509), [#510](https://github.com/Infumia/InfumiaLib/issues/510), [#546](https://github.com/Infumia/InfumiaLib/issues/546), [#547](https://github.com/Infumia/InfumiaLib/issues/547), [#548](https://github.com/Infumia/InfumiaLib/issues/548), [#549](https://github.com/Infumia/InfumiaLib/issues/549), [#624](https://github.com/Infumia/InfumiaLib/issues/624), [#633](https://github.com/Infumia/InfumiaLib/issues/633), [#635](https://github.com/Infumia/InfumiaLib/issues/635), [#636](https://github.com/Infumia/InfumiaLib/issues/636), [#637](https://github.com/Infumia/InfumiaLib/issues/637), [#639](https://github.com/Infumia/InfumiaLib/issues/639), [#643](https://github.com/Infumia/InfumiaLib/issues/643), [#644](https://github.com/Infumia/InfumiaLib/issues/644), [#645](https://github.com/Infumia/InfumiaLib/issues/645), [#646](https://github.com/Infumia/InfumiaLib/issues/646).

**Comment by 0pdd** [comment]
@portlek 2 puzzles [#unknown](), [#unknown]() are still not solved.
